# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ac2a9da4b8b50954539cfedd6d045bd6"
name = "NestGallery"
application_url = "https://gallerynest.kaswebtechsolutions.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_files"

[auth]
redirect_urls = [ "https://gallerynest.kaswebtechsolutions.com/auth/callback" ]

[app_proxy]
url = "https://gallerynest.kaswebtechsolutions.com/apps/gallery-nest"
subpath = "gallery-nest"
prefix = "apps"
